#!/usr/bin/env bash
set -e
BASE_URL="${BASE_URL:-https://logos-gateway.amrta.workers.dev}"
cd "$(dirname "$0")/.."

if [ -n "$CLOUDFLARE_API_TOKEN" ]; then
  echo ">>> 部署 Worker（含 /feed/storage、/feed/upload、/feed/export、/feed/language-upload、/test）..."
  npx -y wrangler deploy worker.js --name logos-gateway --config wrangler.toml --env="" 2>&1 || true
  sleep 3
fi

echo ""
echo ">>> 1. 存储状态 GET $BASE_URL/feed/storage"
STORAGE=$(curl -s "$BASE_URL/feed/storage" || echo '{"error":"request_failed"}')
if command -v jq >/dev/null 2>&1; then echo "$STORAGE" | jq -c .; else echo "$STORAGE"; fi

if echo "$STORAGE" | grep -q '"error":"Unknown endpoint"'; then
  echo ""
  echo ">>> 线上 Worker 仍是旧版，无 /feed 路由。请执行以下之一："
  echo "    本地: CLOUDFLARE_API_TOKEN=xxx ./scripts/worker_deploy_and_check.sh"
  echo "    或: push worker.js + wrangler.toml 到 main 触发 GitHub Actions 部署"
  exit 0
fi

echo ""
echo ">>> 2. 上传测试 POST $BASE_URL/feed/upload (2 条)"
UPLOAD=$(curl -s -X POST "$BASE_URL/feed/upload" \
  -H "Content-Type: application/json" \
  -d '{"intents":["diagnostic_a","diagnostic_b"]}' || echo '{"error":"request_failed"}')
if command -v jq >/dev/null 2>&1; then echo "$UPLOAD" | jq -c .; else echo "$UPLOAD"; fi

D1_OK=$(echo "$STORAGE" | jq -r '.d1 // false' 2>/dev/null || echo "false")
D1_ERR=$(echo "$STORAGE" | jq -r '.d1_error // empty' 2>/dev/null)
SUP_OK=$(echo "$STORAGE" | jq -r '.supabase // false' 2>/dev/null || echo "false")
STORE=$(echo "$UPLOAD" | jq -r '.stored // .error // "unknown"' 2>/dev/null || echo "$UPLOAD")

echo ""
if [ "$STORE" = "d1" ]; then
  echo ">>> D1 写入正常。"
elif [ "$STORE" = "supabase" ]; then
  echo ">>> Supabase 写入正常。"
elif [ "$D1_OK" = "true" ] && [ -n "$D1_ERR" ]; then
  echo ">>> D1 已绑定但异常: $D1_ERR（首次 upload 会尝试自动建表 intents）"
elif [ "$SUP_OK" = "true" ] && (echo "$UPLOAD" | grep -q "supabase\|502"); then
  echo ">>> Supabase 已配置但写入失败，请在 Supabase SQL Editor 建表:"
  echo "    CREATE TABLE IF NOT EXISTS intents (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, human text);"
  echo "    若启用 RLS，需为 anon 添加 INSERT/SELECT 策略。"
else
  echo ">>> 存储: $STORE"
  if [ "$D1_OK" != "true" ] && [ "$SUP_OK" != "true" ]; then
    echo "    仅用 D1 时 toml 已含 D1 绑定，部署后应出现 d1: true。若需 Supabase 请用 Dashboard「Encrypt」添加 SUPABASE_*，避免下次部署清掉。"
  fi
fi

echo ""
echo ">>> 3. 全端点自测 GET $BASE_URL/test"
TEST=$(curl -s "$BASE_URL/test" || echo '{"error":"request_failed"}')
if echo "$TEST" | grep -q '"error":"Unknown endpoint"'; then
  echo "    线上无 /test 路由，请用当前 repo 的 worker.js 部署后再跑本脚本。"
else
  if command -v jq >/dev/null 2>&1; then echo "$TEST" | jq -c .; else echo "$TEST"; fi
fi

echo ""
echo ">>> 4. 导出 JSONL 前 2 行 GET $BASE_URL/feed/export"
EXPORT=$(curl -s "$BASE_URL/feed/export" | head -2)
if echo "$EXPORT" | grep -q '"error":"Unknown endpoint"'; then
  echo "    线上无 /feed/export。"
else
  echo "$EXPORT"
fi
